export enum types {
  SIGN_UP = "auth/SIGN_UP",
  SIGN_IN = "auth/SIGN_IN",

  SET_COLUMNS = "columns/SET_COLUMNS",
  FETCH_COLUMNS = "columns/FETCH_COLUMNS",
  CREATE_COLUMN = "column/CREATE_COLUMN",
  CREATE_COLUMN_REQUESTED = "column/CREATE_COLUMN_REQUESTED",
  UPDATE_COLUMN = "column/UPDATE_COLUMN",
  UPDATE_COLUMN_REQUESTED = "column/UPDATE_COLUMN_REQUESTED",
  DELETE_COLUMN = "column/DELETE_COLUMN",
  DELETE_COLUMN_REQUESTED = "column/DELETE_COLUMN_REQUESTED",
  GET_COLUMN = "column/GET_COLUMN",

  FETCH_PRAYERS = "prayers/FETCH_PRAYERS",
  GET_PRAYER = "prayers/GET_PRAYER",
  DELETE_PRAYER = "prayers/DELETE_PRAYER",
  CREATE_PRAYER = "prayers/CREATE_PRAYER",

  FETCH_COMMENTS = "comments/FETCH_COMMENT",
  CREATE_COMMENT = "comments/CREATE_COMMENT",
  DELETE_COMMENT = "comments/DELETE_COMMENT",

  APP_SET_STATUS = "'app/SET-STATUS'"
}
